name: skillet

views:

  - name: ''
    class: CNCView
    menu: Example
    menu_option: Welcome
    attributes:
      template_name: pan_cnc/welcome.html
    context:
      title: Skillet
      description: Example CNC Application
      documentation_link: https://github.com/scotchoaf/cnc-skeleton/blob/master/src/cnc-app-name/.pan-cnc.yaml
      next: workflow00

  - name: workflow00
    class: ExampleAppView
    menu: Example
    menu_option: Test Menu Option
    attributes:
      header: Step 1
      title: Select Configuration Option
      next_url: workflow01
      snippet: simple_example
      fields_to_render:
        - var_name
        - var_name_again

  - name: workflow01
    class: ExampleAppPasswordView
    attributes:
      snippet: simple_example
      fields_to_render:
        - example_password


