name: simple_example
label: Example App Skillet
description: Basic example skillet
type: template
extends:

labels:
    some_key: some_value

variables:
- name: var_name
  description: Variable Description
  default: here is a default value
  type_hint: text
- name: var_name_again
  description: Another Variable
  default: hi there
  type_hint: dropdown
  dd_list:
    - key: Option 1
      value: selected_value_key_0001
    - key: Option 2
      value: some_other_value
- name: example_password
  description: example_password
  default:
  type_hint: password

snippets:
